-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 19:12:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema appgym_mvc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `appgym_mvc` ;

-- -----------------------------------------------------
-- Schema appgym_mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appgym_mvc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `appgym_mvc` ;

-- -----------------------------------------------------
-- Table `appgym_mvc`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appgym_mvc`.`servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `precio` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appgym_mvc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appgym_mvc`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `apellidos` VARCHAR(60) NULL DEFAULT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `password` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `admin` TINYINT(1) NULL DEFAULT NULL,
  `confirmado` TINYINT(1) NULL DEFAULT NULL,
  `token` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appgym_mvc`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appgym_mvc`.`sesiones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `usuarioId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sesiones_ibfk_1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `appgym_mvc`.`usuarios` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `usuarioId` ON `appgym_mvc`.`sesiones` (`usuarioId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `appgym_mvc`.`sesionesservicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appgym_mvc`.`sesionesservicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sesionId` INT NULL DEFAULT NULL,
  `servicioId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sesionesservicios_ibfk_3`
    FOREIGN KEY (`sesionId`)
    REFERENCES `appgym_mvc`.`sesiones` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `sesionesservicios_ibfk_4`
    FOREIGN KEY (`servicioId`)
    REFERENCES `appgym_mvc`.`servicios` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `sesionId` ON `appgym_mvc`.`sesionesservicios` (`sesionId` ASC) VISIBLE;

CREATE INDEX `servicioId` ON `appgym_mvc`.`sesionesservicios` (`servicioId` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
